apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcehg
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: fcehg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fcehg
    spec:
      containers:
      - name: fcehg
        image: prskid1000/fcehg
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fcehg
  namespace: default
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.43.142
  selector:
    name: fcehg
  ports:
  - port: 3000
    targetPort: 3000