apiVersion: v1
kind: Service
metadata:
  name: fcehg-service
  labels:
    app: fechg
spec:
  type: LoadBalancer
  selector:
    app: fcehg
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3000
      nodePort: 30000